name: CI Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Configure Go Module Cache
      run: |
        mkdir -p $HOME/.cache/go-mod
        export GOMODCACHE=$HOME/.cache/go-mod
        echo "export GOMODCACHE=$HOME/.cache/go-mod" >> $GITHUB_ENV

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: $HOME/.cache/go-mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run Tests
      run: go test ./...

  docker-validate:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t microservice-template:test .

    - name: Start Container
      run: docker run -d --name microservice-template-container -p 8080:8080 microservice-template:test

    - name: Validate Container
      run: curl -f http://localhost:8080/api/example || exit 1

    - name: Cleanup Cache and Containers
      if: always()
      run: |
        docker stop microservice-template-container || true
        docker rm microservice-template-container || true
        rm -rf $HOME/.cache/go-mod || true
